name: delete_un_used_assets
description: A command line tool to delete un used assets
version: 1.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  path: ^1.8.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
